[package]
name = "sqlite-jiff"
version = "0.0.1-alpha.2"
edition = "2021"

[dependencies]
#sqlite-loadable = "0.0.6-alpha.6"
sqlite-loadable = {git = "https://github.com/asg017/sqlite-loadable-rs.git", rev = "87c141fd0a0feac7328cc66dd605704022189195"}
jiff = "0.1.0"
bitflags = "2.9.1"

[lib]
crate-type=["lib", "staticlib", "cdylib"]
