name: "Test"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-extension:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux-x86_64
          - os: ubuntu-22.04-arm
            target: linux-aarch64
          - os: macos-13
            target: macos-x86_64
          - os: macos-14
            target: macos-aarch64
          - os: windows-2019
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable
      - run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/asg017/solite/releases/download/0.0.1-alpha.7/solite-cli-installer.sh | sh
      - run: TZ=America/Los_Angeles solite snap tests/snapshot.sql
      - uses: actions/upload-artifact@v4
        with:
          name: sqlite-jiff-${{ matrix.target }}-extension
          path: dist/*
